let firstName = "Sajeed";
let middleName = "Enayet";
let thirdName = "Aninda";
let fullName = firstName + middleName + thirdName;
// console.log(fullName);
fullName = firstName + " " + middleName + " " + thirdName;
// console.log(fullName);
let concattt = firstName.concat(middleName, thirdName);
console.log(concattt);
concattt = firstName.concat(" ", middleName, " ", thirdName);
console.log(concattt);
