// console.log(Math.pow(2, 3));
// console.log(Math.pow(2, 4));
// console.log(Math.pow(1, 2));
// console.log(Math.pow(4, 2));
// console.log(Math.pow(5, 5));
// console.log(Math.abs(-4));
// console.log(Math.abs(-6));
// console.log(Math.abs(10));
// console.log(Math.abs(-55));
// console.log(Math.abs(-30));
// console.log(Math.ceil(-4.3));
// console.log(Math.ceil(5.6));
// console.log(Math.ceil(3.4));
// console.log(Math.ceil(6.7));
// console.log(Math.ceil(9.8));
// console.log(Math.floor(4.6));
// console.log(Math.floor(3.99));
// console.log(Math.floor(3.56));
// console.log(Math.floor(55.66));
// console.log(Math.floor(12.12));
// console.log(Math.round(4.33));
// console.log(Math.round(1.8));
// console.log(Math.round(78.78));
// console.log(Math.round(45.56));
// console.log(Math.round(45.46));
// console.log(Math.sqrt(8));
// console.log(Math.sqrt(9));
// console.log(Math.sqrt(25));
// console.log(Math.sqrt(36));
// console.log(Math.sqrt(81));
// console.log(Math.round(Math.random() * 100));